name: 'Setup TeX Live'
description: 'GHA action to setup TeX Live'
inputs:
  cache-key:
    default: 'texlive'
  packages-path:
    default: ${{ github.action_path }}/texlive.packages
  profile-path:
    default: ${{ github.action_path }}/texlive.profile
  installation-path:
    default: ${{ runner.tool_cache }}/texlive
outputs: {}
runs:
  using: "composite"
  steps:
    - name: Cache TeX Live installation
      uses: actions/cache@v2
      id: cache-texlive
      with:
        path: ${{ inputs.installation-path }}
        key: ${{ inputs.cache-key }}-${{ hashFiles(inputs.profile-path, inputs.packages-path) }}
        restore-keys: ${{ inputs.cache-key }}-

    - name: Install TeX Live distribution
      if: steps.cache-texlive.outputs.cache-hit != 'true'
      env:
        TEXLIVE_INSTALL_PREFIX: ${{ inputs.installation-path }}
        TEXLIVE_PROFILE_PATH: ${{ inputs.profile-path }}
      shell: bash
      run: |
        cd ${{ runner.temp }}
        wget -q http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
        tar -xzf install-tl-unx.tar.gz
        cd install-tl-20* || exit 1
        ./install-tl --portable --profile="$TEXLIVE_PROFILE_PATH"
        echo "$TEXLIVE_INSTALL_PREFIX/bin/$(ls $TEXLIVE_INSTALL_PREFIX/bin)" >> $GITHUB_PATH
    - name: Install TeX Live packages
      if: steps.cache-texlive.outputs.cache-hit != 'true'
      env:
        TEXLIVE_PACKAGES_PATH: ${{ inputs.packages-path }}
      shell: bash
      run: |
        while IFS=\= read pkg; do TEXLIVE_PACKAGES+=($pkg); done < <(grep -v '^$' "$TEXLIVE_PACKAGES_PATH")
        tlmgr install "${TEXLIVE_PACKAGES[@]}"

    - name: Update TeX Live distribution
      if: steps.cache-texlive.outputs.cache-hit == 'true'
      env:
        TEXLIVE_INSTALL_PREFIX: ${{ inputs.installation-path }}
      shell: bash
      run: |
        PATH=$TEXLIVE_INSTALL_PREFIX/bin/$(ls $TEXLIVE_INSTALL_PREFIX/bin):$PATH
        tlmgr update --self
        tlmgr update --all
        echo "$TEXLIVE_INSTALL_PREFIX/bin/$(ls $TEXLIVE_INSTALL_PREFIX/bin)" >> $GITHUB_PATH
